import React, { createContext, useContext, useEffect, useState } from 'react';
import { Technician, Schedule, Target, Equipment, EquipmentLoan, Material, MaintenanceRecord, DocumentationItem, NotificationItem, AdminUser, SystemSettings, ToastMessage, EquipmentCondition, SurveyItem, Installation, EquipmentUnit, SurveyMeasurement } from '../types';
import { initialAdminProfile, initialSystemSettings } from '../data/initialData';
import { supabase, checkSupabaseConnection, getStoredSupabaseConfig, SupabaseConfig } from '../lib/supabase';

export type PageId = 'dashboard' | 'survey' | 'pemasangan' | 'teknisi' | 'jadwal' | 'target' | 'peralatan' | 'peminjaman' | 'material' | 'maintenance' | 'laporan' | 'dokumentasi' | 'notifikasi' | 'pengaturan';
interface AppContextType {
  isAuthenticated: boolean; authLoading: boolean; currentUser: AdminUser; activePage: PageId; navigate: (page: PageId) => void;
  login: (email: string, pass: string, remember: boolean) => Promise<boolean>; logout: () => Promise<void>; updateCurrentUser: (data: Partial<AdminUser>) => Promise<boolean>;
  managedUsers: AdminUser[]; refreshManagedUsers: () => Promise<void>; createManagedUser: (data: { name: string; email: string; password: string; role: string }) => Promise<boolean>;
  notifications: NotificationItem[]; unreadNotificationCount: number; markNotificationAsRead: (id: string) => Promise<boolean>; markAllNotificationsAsRead: () => Promise<boolean>;
  toasts: ToastMessage[]; showToast: (title: string, message?: string, type?: ToastMessage['type']) => void; removeToast: (id: string) => void;
  technicians: Technician[]; addTechnician: (data: Omit<Technician, 'id' | 'activeSchedules' | 'currentTargetPercentage'>) => Promise<boolean>; updateTechnician: (id: string, data: Partial<Technician>) => Promise<boolean>; deleteTechnician: (id: string) => Promise<boolean>;
  schedules: Schedule[]; addSchedule: (data: Omit<Schedule, 'id'>) => Promise<boolean>; updateSchedule: (id: string, data: Partial<Schedule>) => Promise<boolean>; deleteSchedule: (id: string) => Promise<boolean>;
  surveys: SurveyItem[]; addSurvey: (data: Omit<SurveyItem, 'id'>) => Promise<boolean>; updateSurvey: (id: string, data: Partial<SurveyItem>) => Promise<boolean>; deleteSurvey: (id: string) => Promise<boolean>;
  installations: Installation[]; addInstallation: (data: Omit<Installation, 'id'>) => Promise<boolean>; updateInstallation: (id: string, data: Partial<Installation>) => Promise<boolean>; deleteInstallation: (id: string) => Promise<boolean>; logInstallationDay: (id: string, day: number, sets: number, notes?: string) => Promise<boolean>;
  targets: Target[]; addTarget: (data: Omit<Target, 'id' | 'progressPercentage' | 'daysRemaining'>) => Promise<boolean>; updateTarget: (id: string, data: Partial<Target>) => Promise<boolean>; deleteTarget: (id: string) => Promise<boolean>;
  equipment: Equipment[]; addEquipment: (data: Omit<Equipment, 'id'>) => Promise<boolean>; updateEquipment: (id: string, data: Partial<Equipment>) => Promise<boolean>; deleteEquipment: (id: string) => Promise<boolean>;
  loans: EquipmentLoan[]; addLoan: (data: Omit<EquipmentLoan, 'id'>) => Promise<boolean>; updateLoan: (id: string, data: Partial<EquipmentLoan>) => Promise<boolean>; deleteLoan: (id: string) => Promise<boolean>; returnLoan: (id: string, dateOrCondition: string | EquipmentCondition, condition?: EquipmentCondition, notes?: string) => Promise<boolean>;
  materials: Material[]; addMaterial: (data: Omit<Material, 'id'>) => Promise<boolean>; updateMaterial: (id: string, data: Partial<Material>) => Promise<boolean>; deleteMaterial: (id: string) => Promise<boolean>;
  maintenanceRecords: MaintenanceRecord[]; addMaintenanceRecord: (data: Omit<MaintenanceRecord, 'id'>) => Promise<boolean>; updateMaintenanceRecord: (id: string, data: Partial<MaintenanceRecord>) => Promise<boolean>; deleteMaintenanceRecord: (id: string) => Promise<boolean>;
  documentations: DocumentationItem[]; addDocumentation: (data: Omit<DocumentationItem, 'id'>) => Promise<boolean>; deleteDocumentation: (id: string) => Promise<boolean>;
  settings: SystemSettings; updateSettings: (data: Partial<SystemSettings>) => Promise<boolean>; resetToDefaultData: () => Promise<void>;
  supabaseStatus: { isConnected: boolean; message: string; latencyMs?: number }; supabaseConfig: SupabaseConfig; updateSupabaseConfig: (url: string, key: string) => Promise<boolean>; refreshSupabaseConnection: () => Promise<void>;
  globalSearchQuery: string; setGlobalSearchQuery: (query: string) => void;
}

const AppContext = createContext<AppContextType | undefined>(undefined);
const today = () => new Date().toISOString().slice(0, 10);
const idFor = (prefix: string) => `${prefix}-${crypto.randomUUID().slice(0, 8)}`;
const errorText = (error: any) => error?.message || 'Operasi Supabase gagal.';
const mapTechnician = (r: any): Technician => ({ id: r.id, name: r.name, phone: r.phone || undefined, status: r.status, joinedDate: r.joined_date });
const mapSchedule = (r: any): Schedule => ({ id: r.id, surveyId: r.survey_id || undefined, installationId: r.installation_id || undefined, date: r.date, time: r.time, type: r.type, sales: r.sales || undefined, technicianId: r.technician_id || '', technicianName: r.technician_name, assistantTechnicianName: r.assistant_technician_name || undefined, customerName: r.customer_name, setsCount: r.sets_count || undefined, location: r.location, status: r.status, notes: r.notes || undefined, createdAt: r.created_at });
const mapMeasurement = (r: any): SurveyMeasurement => ({ id: r.id, roomName: r.room_name, widthCm: Number(r.width_cm), heightCm: Number(r.height_cm), fabricType: r.fabric_type, mechanism: r.mechanism, notes: r.notes || undefined });
const mapSurvey = (r: any, measurements: SurveyMeasurement[], techIds: string[]): SurveyItem => ({ id: r.id, customerName: r.customer_name, location: r.location, sales: r.sales_name || '', technicianId: r.technician_id || '', technicianName: r.technician_name, technicianIds: techIds.length ? techIds : [r.technician_id].filter(Boolean), technicianNames: [r.technician_name, r.assistant_technician_name].filter(Boolean), assistantTechnicianName: r.assistant_technician_name || undefined, date: r.survey_date, time: r.survey_time, status: r.status, notes: r.notes || undefined, measurements });
const mapInstallation = (r: any, items: any[]): Installation => ({ id: r.id, projectName: r.project_name, customerName: r.customer_name, location: r.location, technicianId: r.technician_id || '', technicianName: r.technician_name, startDate: r.start_date, endDate: r.end_date || undefined, totalSets: r.total_sets, completedSets: r.completed_sets, progressPercentage: r.progress_percentage, status: r.status, notes: r.notes || undefined, dailyProgress: items.map((i) => ({ dayNumber: i.day_number, date: i.work_date, setsInstalled: i.sets_installed, technicianName: i.technician_name || undefined, notes: i.notes || undefined })) });
const mapTarget = (r: any): Target => ({ id: r.id, technicianId: r.technician_id || '', technicianName: r.technician_name, periodStart: r.period_start, periodEnd: r.period_end, targetSets: r.target_sets, actualSets: r.actual_sets, progressPercentage: r.progress_percentage, status: r.status, daysRemaining: Math.max(0, Math.ceil((new Date(r.period_end).getTime() - Date.now()) / 86400000)) });
const mapUnit = (r: any): EquipmentUnit => ({ id: r.id, equipmentId: r.equipment_id, code: r.unit_code, status: r.status, condition: r.condition, serialNumber: r.serial_number || undefined, currentBorrower: r.current_borrower || undefined, currentBorrowerId: r.current_borrower_id || undefined, lastBorrowDate: r.last_borrow_date || undefined, lastReturnDate: r.last_return_date || undefined });
const mapEquipment = (r: any, units: EquipmentUnit[]): Equipment => { const borrowed = units.find((u) => u.status === 'Dipinjam'); const status = borrowed ? 'Dipinjam' : units.some((u) => u.status === 'Maintenance') ? 'Maintenance' : units.some((u) => u.status === 'Rusak') ? 'Rusak' : 'Tersedia'; return { id: r.id, code: r.code || undefined, name: r.name, category: r.category, status, condition: units.length && units.every((u) => u.condition === 'Perlu Servis') ? 'Perlu Servis' : r.condition, serialNumber: r.serial_number || undefined, currentBorrower: borrowed?.currentBorrower, currentBorrowerId: borrowed?.currentBorrowerId, lastMaintained: r.last_maintained || undefined, notes: r.notes || undefined, units, unitCount: units.length }; };
const mapLoan = (r: any): EquipmentLoan => ({ id: r.id, equipmentId: r.equipment_id, unitId: r.unit_id || undefined, unitCode: r.unit_code || undefined, equipmentCode: r.equipment_code || undefined, equipmentName: r.equipment_name, borrowerName: r.borrower_name, technicianId: r.technician_id, borrowDate: r.borrow_date, borrowedAt: r.borrowed_at, estimatedReturnDate: r.estimated_return_date, actualReturnDate: r.actual_return_date, returnedAt: r.returned_at, status: r.status, returnCondition: r.return_condition || undefined, notes: r.notes || undefined });
const mapMaterial = (r: any): Material => ({ id: r.id, code: r.code || undefined, name: r.name, category: r.category, stock: Number(r.stock), unit: r.unit, minStock: Number(r.min_stock), status: r.status, notes: r.notes || undefined, lastRestocked: r.last_restocked || undefined });
const mapMaintenance = (r: any): MaintenanceRecord => ({ id: r.id, equipmentId: r.equipment_id, equipmentCode: r.equipment_code || undefined, equipmentName: r.equipment_name, maintenanceType: r.maintenance_type, scheduledDate: r.scheduled_date, cost: Number(r.cost), status: r.status, technicianInCharge: r.technician_in_charge || undefined, notes: r.notes || undefined });
const mapDocument = (r: any): DocumentationItem => ({ id: r.id, title: r.title, type: r.type || undefined, technicianId: r.technician_id || undefined, technicianName: r.technician_name, location: r.location || undefined, date: r.date, imageUrl: r.image_url, description: r.description || '', setsCount: r.sets_count || undefined, notes: r.notes || undefined });
const mapNotification = (r: any): NotificationItem => ({ id: r.id, type: r.type, title: r.title, message: r.message, timestamp: r.created_at, relativeTime: r.created_at, read: r.read, linkPage: r.link_page || 'dashboard' });

export const AppProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [isAuthenticated, setIsAuthenticated] = useState(false); const [authLoading, setAuthLoading] = useState(true); const [currentUser, setCurrentUser] = useState<AdminUser>(initialAdminProfile); const [activePage, setActivePage] = useState<PageId>('dashboard'); const [managedUsers, setManagedUsers] = useState<AdminUser[]>([]); const [globalSearchQuery, setGlobalSearchQuery] = useState('');
  const [technicians, setTechnicians] = useState<Technician[]>([]); const [schedules, setSchedules] = useState<Schedule[]>([]); const [surveys, setSurveys] = useState<SurveyItem[]>([]); const [installations, setInstallations] = useState<Installation[]>([]); const [targets, setTargets] = useState<Target[]>([]); const [equipment, setEquipment] = useState<Equipment[]>([]); const [loans, setLoans] = useState<EquipmentLoan[]>([]); const [materials, setMaterials] = useState<Material[]>([]); const [maintenanceRecords, setMaintenanceRecords] = useState<MaintenanceRecord[]>([]); const [documentations, setDocumentations] = useState<DocumentationItem[]>([]); const [notifications, setNotifications] = useState<NotificationItem[]>([]); const [settings, setSettings] = useState<SystemSettings>(initialSystemSettings); const [toasts, setToasts] = useState<ToastMessage[]>([]); const [supabaseConfig, setSupabaseConfig] = useState<SupabaseConfig>(getStoredSupabaseConfig()); const [supabaseStatus, setSupabaseStatus] = useState<{ isConnected: boolean; message: string; latencyMs?: number }>({ isConnected: false, message: 'Menguji koneksi Supabase...' });
  const showToast = (title: string, message?: string, type: ToastMessage['type'] = 'success') => { const id = `toast-${Date.now()}`; setToasts((p) => [...p, { id, title, message, type }]); window.setTimeout(() => setToasts((p) => p.filter((t) => t.id !== id)), 4500); }; const removeToast = (id: string) => setToasts((p) => p.filter((t) => t.id !== id));
  const refreshSupabaseConnection = async () => { const result = await checkSupabaseConnection(); setSupabaseStatus({ isConnected: result.isConnected, message: result.message, latencyMs: result.latencyMs }); };
  const refreshTechniciansFromSupabase = async () => { const { data, error } = await supabase.from('technicians').select('*').order('name'); if (error) throw error; setTechnicians((data || []).map(mapTechnician)); };
  const refreshSchedulesFromSupabase = async () => { const { data, error } = await supabase.from('schedules').select('*').order('date'); if (error) throw error; setSchedules((data || []).map(mapSchedule)); };
  const refreshSurveysFromSupabase = async () => { const [{ data, error }, { data: measurements, error: measurementError }, { data: links, error: linkError }] = await Promise.all([supabase.from('surveys').select('*').order('survey_date', { ascending: false }), supabase.from('survey_measurements').select('*'), supabase.from('survey_technicians').select('*')]); if (error || measurementError || linkError) throw error || measurementError || linkError; setSurveys((data || []).map((r) => mapSurvey(r, (measurements || []).filter((m) => m.survey_id === r.id).map(mapMeasurement), (links || []).filter((l) => l.survey_id === r.id).map((l) => l.technician_id)))); };
  const refreshInstallationsFromSupabase = async () => { const [{ data, error }, { data: items, error: itemError }] = await Promise.all([supabase.from('installations').select('*').order('start_date', { ascending: false }), supabase.from('installation_items').select('*').order('day_number')]); if (error || itemError) throw error || itemError; setInstallations((data || []).map((r) => mapInstallation(r, (items || []).filter((i) => i.installation_id === r.id)))); };
  const refreshTargetsFromSupabase = async () => { const { data, error } = await supabase.from('work_targets').select('*').order('period_end'); if (error) throw error; setTargets((data || []).map(mapTarget)); };
  const refreshEquipmentFromSupabase = async () => { const [{ data, error }, { data: units, error: unitError }] = await Promise.all([supabase.from('equipment').select('*').order('name'), supabase.from('equipment_units').select('*')]); if (error || unitError) throw error || unitError; setEquipment((data || []).map((r) => mapEquipment(r, (units || []).filter((u) => u.equipment_id === r.id).map(mapUnit)))); };
  const refreshLoansFromSupabase = async () => { const { data, error } = await supabase.from('equipment_loans').select('*').order('borrowed_at', { ascending: false }); if (error) throw error; setLoans((data || []).map(mapLoan)); }; const refreshMaterialsFromSupabase = async () => { const { data, error } = await supabase.from('materials').select('*').order('name'); if (error) throw error; setMaterials((data || []).map(mapMaterial)); }; const refreshMaintenanceFromSupabase = async () => { const { data, error } = await supabase.from('maintenance').select('*').order('scheduled_date'); if (error) throw error; setMaintenanceRecords((data || []).map(mapMaintenance)); }; const refreshDocumentationsFromSupabase = async () => { const { data, error } = await supabase.from('documents').select('*').order('date', { ascending: false }); if (error) throw error; setDocumentations((data || []).map(mapDocument)); }; const refreshNotificationsFromSupabase = async () => { const { data, error } = await supabase.from('notifications').select('*').order('created_at', { ascending: false }); if (error) throw error; setNotifications((data || []).map(mapNotification)); };
  const refreshAllData = async () => { await Promise.all([refreshTechniciansFromSupabase(), refreshSchedulesFromSupabase(), refreshSurveysFromSupabase(), refreshInstallationsFromSupabase(), refreshTargetsFromSupabase(), refreshEquipmentFromSupabase(), refreshLoansFromSupabase(), refreshMaterialsFromSupabase(), refreshMaintenanceFromSupabase(), refreshDocumentationsFromSupabase(), refreshNotificationsFromSupabase()]); };
  const loadProfile = async (user: any) => { const { data } = await supabase.from('profiles').select('id,name,email,role_id,phone,avatar_url').eq('id', user.id).maybeSingle(); setCurrentUser(data ? { id: data.id, name: data.name, email: data.email, role: data.role_id, phone: data.phone || undefined, avatarUrl: data.avatar_url || undefined } : { ...initialAdminProfile, id: user.id, name: user.user_metadata?.name || user.email, email: user.email || '' }); if (user.user_metadata?.operational_settings) setSettings((current) => ({ ...current, ...user.user_metadata.operational_settings })); };
  useEffect(() => { refreshSupabaseConnection(); let mounted = true; supabase.auth.getSession().then(async ({ data: { session } }) => { if (!mounted) return; setIsAuthenticated(Boolean(session)); if (session?.user) { await loadProfile(session.user); await refreshAllData().catch((error) => showToast('Data gagal dimuat', errorText(error), 'error')); } setAuthLoading(false); }); const { data } = supabase.auth.onAuthStateChange(async (_event, session) => { setIsAuthenticated(Boolean(session)); if (session?.user) { await loadProfile(session.user); await refreshAllData().catch((error) => showToast('Data gagal dimuat', errorText(error), 'error')); } else setCurrentUser(initialAdminProfile); setAuthLoading(false); }); return () => { mounted = false; data.subscription.unsubscribe(); }; }, []);
  const mutation = async (label: string, action: () => Promise<void>, refresh: () => Promise<void> = refreshAllData) => { try { await action(); await refresh(); showToast(label); return true; } catch (error) { showToast(`${label} gagal`, errorText(error), 'error'); return false; } };
  const login = async (email: string, pass: string, _remember: boolean) => { const { data, error } = await supabase.auth.signInWithPassword({ email: email.trim(), password: pass }); if (error || !data.session) { showToast('Login gagal', errorText(error), 'error'); return false; } await loadProfile(data.user); try { await refreshAllData(); } catch (refreshError) { showToast('Data gagal dimuat', errorText(refreshError), 'error'); } showToast('Login Berhasil', `Selamat datang, ${data.user.email}.`); return true; }; const logout = async () => { await supabase.auth.signOut(); setIsAuthenticated(false); setCurrentUser(initialAdminProfile); };
  const updateCurrentUser = async (data: Partial<AdminUser>) => mutation('Profil diperbarui', async () => { const { error } = await supabase.from('profiles').update({ name: data.name, email: data.email, phone: data.phone, avatar_url: data.avatarUrl }).eq('id', currentUser.id); if (error) throw error; setCurrentUser((previous) => ({ ...previous, ...data })); });
  const refreshManagedUsers = async () => { const { data, error } = await supabase.from('profiles').select('id,name,email,role_id,phone,avatar_url').order('name'); if (error) throw error; setManagedUsers((data || []).map((r) => ({ id: r.id, name: r.name, email: r.email, role: r.role_id, phone: r.phone || undefined, avatarUrl: r.avatar_url || undefined }))); }; const createManagedUser = async (data: { name: string; email: string; password: string; role: string }) => { try { const { error } = await supabase.functions.invoke('admin-create-user', { body: data }); if (error) throw error; await refreshManagedUsers(); showToast('User Berhasil Dibuat'); return true; } catch (error) { showToast('User gagal dibuat', errorText(error), 'error'); return false; } };
  const addTechnician = async (data: Omit<Technician, 'id' | 'activeSchedules' | 'currentTargetPercentage'>) => mutation('Teknisi ditambahkan', async () => { const { error } = await supabase.from('technicians').insert({ id: idFor('TKN'), name: data.name, phone: data.phone, status: data.status, joined_date: data.joinedDate || today() }); if (error) throw error; }); const updateTechnician = async (id: string, data: Partial<Technician>) => mutation('Data teknisi diperbarui', async () => { const { error } = await supabase.from('technicians').update({ name: data.name, phone: data.phone, status: data.status, joined_date: data.joinedDate }).eq('id', id); if (error) throw error; }); const deleteTechnician = async (id: string) => mutation('Teknisi dihapus', async () => { const { error } = await supabase.from('technicians').delete().eq('id', id); if (error) throw error; });
  const normalizeScheduleRelations = (data: Schedule | Omit<Schedule, 'id'>) => {
    const surveyId = typeof data.surveyId === 'string' && data.surveyId.trim() ? data.surveyId : null;
    const installationId = typeof data.installationId === 'string' && data.installationId.trim() ? data.installationId : null;
    if (data.type === 'Survey') {
      if (!surveyId || !surveys.some((survey) => survey.id === surveyId)) throw new Error('Survey tidak ditemukan.');
      return { survey_id: surveyId, installation_id: null };
    }
    if (data.type === 'Pemasangan') {
      if (!installationId || !installations.some((installation) => installation.id === installationId)) throw new Error('Pemasangan tidak ditemukan.');
      return { survey_id: null, installation_id: installationId };
    }
    return { survey_id: null, installation_id: null };
  };
  const addSchedule = async (data: Omit<Schedule, 'id'>) => mutation('Jadwal ditambahkan', async () => { const relations = normalizeScheduleRelations(data); const { error } = await supabase.from('schedules').insert({ id: idFor('SCH'), ...relations, date: data.date, time: data.time, type: data.type, sales: data.sales, technician_id: data.technicianId || null, technician_name: data.technicianName, assistant_technician_name: data.assistantTechnicianName, customer_name: data.customerName, sets_count: data.setsCount, location: data.location, status: data.status, notes: data.notes }); if (error) throw error; }); const updateSchedule = async (id: string, data: Partial<Schedule>) => mutation('Jadwal diperbarui', async () => { const current = schedules.find((schedule) => schedule.id === id); if (!current) throw new Error('Jadwal tidak ditemukan.'); const merged = { ...current, ...data }; const relations = normalizeScheduleRelations(merged); const { error } = await supabase.from('schedules').update({ ...relations, date: merged.date, time: merged.time, type: merged.type, sales: merged.sales, technician_id: merged.technicianId || null, technician_name: merged.technicianName, assistant_technician_name: merged.assistantTechnicianName, customer_name: merged.customerName, sets_count: merged.setsCount, location: merged.location, status: merged.status, notes: merged.notes }).eq('id', id); if (error) throw error; }); const deleteSchedule = async (id: string) => mutation('Jadwal dihapus', async () => { const { error } = await supabase.from('schedules').delete().eq('id', id); if (error) throw error; });
  const addSurvey = async (data: Omit<SurveyItem, 'id'>) => mutation('Survey ditambahkan', async () => { const id = idFor('SRV'); const { error } = await supabase.from('surveys').insert({ id, customer_name: data.customerName, location: data.location, sales_name: data.sales, technician_id: data.technicianId, technician_name: data.technicianName, assistant_technician_name: data.assistantTechnicianName, survey_date: data.date || today(), survey_time: data.time || '09:00', status: data.status, notes: data.notes }); if (error) throw error; const techIds = data.technicianIds?.length ? data.technicianIds : [data.technicianId]; if (techIds.length) { const result = await supabase.from('survey_technicians').insert(techIds.map((technician_id) => ({ survey_id: id, technician_id }))); if (result.error) throw result.error; } if (data.measurements?.length) { const result = await supabase.from('survey_measurements').insert(data.measurements.map((m) => ({ survey_id: id, room_name: m.roomName, width_cm: m.widthCm, height_cm: m.heightCm, fabric_type: m.fabricType, mechanism: m.mechanism, notes: m.notes }))); if (result.error) throw result.error; } });
  const updateSurvey = async (id: string, data: Partial<SurveyItem>) => mutation('Data survey diperbarui', async () => { const current = surveys.find((s) => s.id === id); const merged = { ...current, ...data } as SurveyItem; const { error } = await supabase.from('surveys').update({ customer_name: merged.customerName, location: merged.location, sales_name: merged.sales, technician_id: merged.technicianId, technician_name: merged.technicianName, assistant_technician_name: merged.assistantTechnicianName, survey_date: merged.date || today(), survey_time: merged.time || '09:00', status: merged.status, notes: merged.notes }).eq('id', id); if (error) throw error; const links = await supabase.from('survey_technicians').delete().eq('survey_id', id); if (links.error) throw links.error; const techIds = merged.technicianIds?.length ? merged.technicianIds : [merged.technicianId]; if (techIds.length) { const linkInsert = await supabase.from('survey_technicians').insert(techIds.map((technician_id) => ({ survey_id: id, technician_id }))); if (linkInsert.error) throw linkInsert.error; } const del = await supabase.from('survey_measurements').delete().eq('survey_id', id); if (del.error) throw del.error; if (merged.measurements?.length) { const result = await supabase.from('survey_measurements').insert(merged.measurements.map((m) => ({ survey_id: id, room_name: m.roomName, width_cm: m.widthCm, height_cm: m.heightCm, fabric_type: m.fabricType, mechanism: m.mechanism, notes: m.notes }))); if (result.error) throw result.error; } }); const deleteSurvey = async (id: string) => mutation('Survey dihapus', async () => { const { error } = await supabase.from('surveys').delete().eq('id', id); if (error) throw error; });
  const addInstallation = async (data: Omit<Installation, 'id'>) => mutation('Pemasangan ditambahkan', async () => { const id = idFor('INS'); const { error } = await supabase.from('installations').insert({ id, project_name: data.projectName, customer_name: data.customerName, location: data.location, technician_id: data.technicianId, technician_name: data.technicianName, start_date: data.startDate || today(), end_date: data.endDate || null, total_sets: data.totalSets, completed_sets: data.completedSets, progress_percentage: data.progressPercentage, status: data.status, notes: data.notes }); if (error) throw error; }); const updateInstallation = async (id: string, data: Partial<Installation>) => mutation('Pemasangan diperbarui', async () => { const current = installations.find((i) => i.id === id); const merged = { ...current, ...data } as Installation; const { error } = await supabase.from('installations').update({ project_name: merged.projectName, customer_name: merged.customerName, location: merged.location, technician_id: merged.technicianId, technician_name: merged.technicianName, start_date: merged.startDate, end_date: merged.endDate || null, total_sets: merged.totalSets, completed_sets: merged.completedSets, progress_percentage: merged.progressPercentage, status: merged.status, notes: merged.notes }).eq('id', id); if (error) throw error; }); const deleteInstallation = async (id: string) => mutation('Pemasangan dihapus', async () => { const { error } = await supabase.from('installations').delete().eq('id', id); if (error) throw error; }); const logInstallationDay = async (id: string, day: number, sets: number, notes?: string) => mutation('Progres harian dicatat', async () => { const item = installations.find((i) => i.id === id); if (!item) throw new Error('Pemasangan tidak ditemukan.'); const completed = item.completedSets + sets; const { error } = await supabase.from('installation_items').insert({ installation_id: id, day_number: day, work_date: today(), sets_installed: sets, technician_name: item.technicianName, notes }); if (error) throw error; const update = await supabase.from('installations').update({ completed_sets: completed, progress_percentage: Math.min(100, Math.round(completed / (item.totalSets || 1) * 100)), status: completed >= item.totalSets ? 'Selesai' : 'Dalam Proses' }).eq('id', id); if (update.error) throw update.error; });
  const addTarget = async (data: Omit<Target, 'id' | 'progressPercentage' | 'daysRemaining'>) => mutation('Target ditambahkan', async () => { const row = data as Omit<Target, 'id' | 'progressPercentage' | 'daysRemaining'> & { projectName?: string; customerName?: string; location?: string }; const { error } = await supabase.from('work_targets').insert({ id: idFor('TGT'), project_name: row.projectName, customer_name: row.customerName, location: row.location, technician_id: data.technicianId, technician_name: data.technicianName, period_start: data.periodStart, period_end: data.periodEnd, target_sets: data.targetSets, actual_sets: data.actualSets, progress_percentage: Math.round(data.actualSets / (data.targetSets || 1) * 100), status: data.status }); if (error) throw error; }); const updateTarget = async (id: string, data: Partial<Target>) => mutation('Target diperbarui', async () => { const current = targets.find((t) => t.id === id); const merged = { ...current, ...data } as Target & { projectName?: string; customerName?: string; location?: string }; const { error } = await supabase.from('work_targets').update({ project_name: merged.projectName, customer_name: merged.customerName, location: merged.location, technician_id: merged.technicianId, technician_name: merged.technicianName, period_start: merged.periodStart, period_end: merged.periodEnd, target_sets: merged.targetSets, actual_sets: merged.actualSets, progress_percentage: Math.round(merged.actualSets / (merged.targetSets || 1) * 100), status: merged.status }).eq('id', id); if (error) throw error; }); const deleteTarget = async (id: string) => mutation('Target dihapus', async () => { const { error } = await supabase.from('work_targets').delete().eq('id', id); if (error) throw error; });
  const addEquipment = async (data: Omit<Equipment, 'id'>) => mutation('Alat ditambahkan', async () => { const id = idFor('EQ'); const { error } = await supabase.from('equipment').insert({ id, code: data.code, name: data.name, category: data.category, status: data.status, condition: data.condition, serial_number: data.serialNumber, last_maintained: data.lastMaintained, notes: data.notes }); if (error) throw error; const units = data.units?.length ? data.units : [{ code: `${data.code || id}-001`, status: data.status, condition: data.condition, serialNumber: data.serialNumber } as EquipmentUnit]; const result = await supabase.from('equipment_units').insert(units.map((u) => ({ equipment_id: id, unit_code: u.code, status: u.status, condition: u.condition, serial_number: u.serialNumber }))); if (result.error) throw result.error; });
  const updateEquipment = async (id: string, data: Partial<Equipment>) => mutation('Data alat diperbarui', async () => { const current = equipment.find((e) => e.id === id); if (!current) throw new Error('Alat tidak ditemukan.'); const merged = { ...current, ...data } as Equipment; const { error } = await supabase.from('equipment').update({ code: merged.code, name: merged.name, category: merged.category, status: merged.status, condition: merged.condition, serial_number: merged.serialNumber, last_maintained: merged.lastMaintained, notes: merged.notes }).eq('id', id); if (error) throw error; const baseUnits = merged.units || current.units || []; const targetCount = Math.max(baseUnits.length, merged.unitCount || 0, 1); const units = Array.from({ length: targetCount }, (_, index) => baseUnits[index] || { id: idFor('UNIT'), equipmentId: id, code: `${merged.code || id}-${String(index + 1).padStart(3, '0')}`, status: merged.status, condition: merged.condition } as EquipmentUnit).map((unit) => ({ ...unit, status: data.status && unit.status !== 'Dipinjam' ? data.status : unit.status, condition: data.condition || unit.condition })); const unitResult = await supabase.from('equipment_units').upsert(units.map((unit) => ({ id: unit.id, equipment_id: id, unit_code: unit.code, status: unit.status, condition: unit.condition, serial_number: unit.serialNumber, current_borrower: unit.currentBorrower, current_borrower_id: unit.currentBorrowerId }))); if (unitResult.error) throw unitResult.error; });
  const deleteEquipment = async (id: string) => mutation('Alat dihapus', async () => { const { error } = await supabase.from('equipment').delete().eq('id', id); if (error) throw error; });
  const addLoan = async (data: Omit<EquipmentLoan, 'id'>) => mutation('Peminjaman dicatat', async () => { const { error } = await supabase.from('equipment_loans').insert({ id: idFor('L'), equipment_id: data.equipmentId, unit_id: data.unitId, unit_code: data.unitCode, equipment_code: data.equipmentCode, equipment_name: data.equipmentName, borrower_name: data.borrowerName, technician_id: data.technicianId, borrow_date: data.borrowDate, borrowed_at: data.borrowedAt || new Date().toISOString(), estimated_return_date: data.estimatedReturnDate, status: data.status, notes: data.notes }); if (error) throw error; }); const updateLoan = async (id: string, data: Partial<EquipmentLoan>) => mutation('Peminjaman diperbarui', async () => { const current = loans.find((loan) => loan.id === id); if (!current) throw new Error('Peminjaman tidak ditemukan.'); const merged = { ...current, ...data }; const { error } = await supabase.from('equipment_loans').update({ unit_id: merged.unitId, unit_code: merged.unitCode, equipment_code: merged.equipmentCode, equipment_name: merged.equipmentName, borrower_name: merged.borrowerName, technician_id: merged.technicianId, borrow_date: merged.borrowDate, borrowed_at: merged.borrowedAt, estimated_return_date: merged.estimatedReturnDate, status: merged.status, actual_return_date: merged.actualReturnDate, returned_at: merged.returnedAt, return_condition: merged.returnCondition, notes: merged.notes }).eq('id', id); if (error) throw error; }); const deleteLoan = async (id: string) => mutation('Peminjaman dihapus', async () => { const { error } = await supabase.from('equipment_loans').delete().eq('id', id); if (error) throw error; }); const returnLoan = async (id: string, dateOrCondition: string | EquipmentCondition, condition?: EquipmentCondition, notes?: string) => { const isCondition = ['Baik', 'Rusak Ringan', 'Perlu Servis'].includes(dateOrCondition); return updateLoan(id, { status: 'Dikembalikan', actualReturnDate: isCondition ? today() : dateOrCondition, returnedAt: new Date().toISOString(), returnCondition: isCondition ? dateOrCondition as EquipmentCondition : condition || 'Baik', notes }); };
  const addMaterial = async (data: Omit<Material, 'id'>) => mutation('Material ditambahkan', async () => { const { error } = await supabase.from('materials').insert({ id: idFor('MAT'), code: data.code, name: data.name, category: data.category, stock: data.stock, unit: data.unit, min_stock: data.minStock, status: data.status, notes: data.notes, last_restocked: data.lastRestocked || today() }); if (error) throw error; }); const updateMaterial = async (id: string, data: Partial<Material>) => mutation('Material diperbarui', async () => { const { error } = await supabase.from('materials').update({ code: data.code, name: data.name, category: data.category, stock: data.stock, unit: data.unit, min_stock: data.minStock, status: data.status, notes: data.notes, last_restocked: data.lastRestocked }).eq('id', id); if (error) throw error; }); const deleteMaterial = async (id: string) => mutation('Material dihapus', async () => { const { error } = await supabase.from('materials').delete().eq('id', id); if (error) throw error; });
  const addMaintenanceRecord = async (data: Omit<MaintenanceRecord, 'id'>) => mutation('Maintenance ditambahkan', async () => { const { error } = await supabase.from('maintenance').insert({ id: idFor('M'), equipment_id: data.equipmentId, equipment_code: data.equipmentCode, equipment_name: data.equipmentName, maintenance_type: data.maintenanceType, scheduled_date: data.scheduledDate, cost: data.cost, status: data.status, technician_in_charge: data.technicianInCharge, notes: data.notes }); if (error) throw error; }); const updateMaintenanceRecord = async (id: string, data: Partial<MaintenanceRecord>) => mutation('Maintenance diperbarui', async () => { const { error } = await supabase.from('maintenance').update({ equipment_id: data.equipmentId, equipment_code: data.equipmentCode, equipment_name: data.equipmentName, maintenance_type: data.maintenanceType, scheduled_date: data.scheduledDate, cost: data.cost, status: data.status, technician_in_charge: data.technicianInCharge, notes: data.notes }).eq('id', id); if (error) throw error; }); const deleteMaintenanceRecord = async (id: string) => mutation('Maintenance dihapus', async () => { const { error } = await supabase.from('maintenance').delete().eq('id', id); if (error) throw error; });
  const addDocumentation = async (data: Omit<DocumentationItem, 'id'>) => mutation('Dokumentasi disimpan', async () => { const { error } = await supabase.from('documents').insert({ id: idFor('DOC'), title: data.title, type: data.type, technician_id: data.technicianId, technician_name: data.technicianName, location: data.location, date: data.date || today(), image_url: data.imageUrl, description: data.description, sets_count: data.setsCount, notes: data.notes }); if (error) throw error; }); const deleteDocumentation = async (id: string) => mutation('Dokumentasi dihapus', async () => { const { error } = await supabase.from('documents').delete().eq('id', id); if (error) throw error; });
  const markNotificationAsRead = async (id: string) => mutation('Notifikasi diperbarui', async () => { const { error } = await supabase.from('notifications').update({ read: true }).eq('id', id); if (error) throw error; }, refreshNotificationsFromSupabase); const markAllNotificationsAsRead = async () => mutation('Notifikasi diperbarui', async () => { const { error } = await supabase.from('notifications').update({ read: true }).eq('read', false); if (error) throw error; }, refreshNotificationsFromSupabase); const updateSettings = async (data: Partial<SystemSettings>) => { const next = { ...settings, ...data }; const { error } = await supabase.auth.updateUser({ data: { operational_settings: next } }); if (error) { showToast('Pengaturan gagal disimpan', errorText(error), 'error'); return false; } setSettings(next); showToast('Pengaturan tersimpan'); return true; }; const resetToDefaultData = async () => { await refreshAllData(); showToast('Data dimuat ulang dari Supabase', undefined, 'info'); }; const updateSupabaseConfig = async (_url: string, _key: string) => { const result = await checkSupabaseConnection(); setSupabaseStatus({ isConnected: result.isConnected, message: result.message, latencyMs: result.latencyMs }); return result.isConnected; }; const navigate = (page: PageId) => { setActivePage(page); window.scrollTo({ top: 0, behavior: 'smooth' }); };
  return <AppContext.Provider value={{ isAuthenticated, authLoading, currentUser, activePage, navigate, login, logout, updateCurrentUser, managedUsers, refreshManagedUsers, createManagedUser, notifications, unreadNotificationCount: notifications.filter((n) => !n.read).length, markNotificationAsRead, markAllNotificationsAsRead, toasts, showToast, removeToast, technicians, addTechnician, updateTechnician, deleteTechnician, schedules, addSchedule, updateSchedule, deleteSchedule, surveys, addSurvey, updateSurvey, deleteSurvey, installations, addInstallation, updateInstallation, deleteInstallation, logInstallationDay, targets, addTarget, updateTarget, deleteTarget, equipment, addEquipment, updateEquipment, deleteEquipment, loans, addLoan, updateLoan, deleteLoan, returnLoan, materials, addMaterial, updateMaterial, deleteMaterial, maintenanceRecords, addMaintenanceRecord, updateMaintenanceRecord, deleteMaintenanceRecord, documentations, addDocumentation, deleteDocumentation, settings, updateSettings, resetToDefaultData, supabaseStatus, supabaseConfig, updateSupabaseConfig, refreshSupabaseConnection, globalSearchQuery, setGlobalSearchQuery }}>{children}</AppContext.Provider>;
};
export const useApp = () => { const context = useContext(AppContext); if (!context) throw new Error('useApp must be used within an AppProvider'); return context; };
